
#
# Module Manifest for Module 'BurntToast
#
# This manifest file is a PowerShell hashtable with all technical requirements for this module
# This module was autogenerated by ISESteroids (http://www.isesteroids.com)
#
# Author   : Windos
#
# Generated: 2015-07-19
#

@{

# Module Loader File
ModuleToProcess = 'loader.psm1'

# Version Number
ModuleVersion = '0.4'

# Unique Module ID
GUID = '751a2aeb-a68f-422e-a2ea-376bdd81612a'

# Module Author
Author = 'Joshua (Windos) King'

# Company
CompanyName = 'king.geek.nz'

# Copyright
Copyright = '(c) 2015 Joshua (Windos) King. All rights reserved.'

# Module Description
Description = 'Module for creating and displaying Toast Notifications on Microsoft Windows 8 and Windows 10 operating systems.'

# Minimum PowerShell Version Required
PowerShellVersion = '3.0'

# Name of Required PowerShell Host
PowerShellHostName = ''

# Minimum Host Version Required
PowerShellHostVersion = ''

# Minimum .NET Framework-Version
DotNetFrameworkVersion = ''

# Minimum CLR (Common Language Runtime) Version
CLRVersion = ''

# Processor Architecture Required (X86, Amd64, IA64)
ProcessorArchitecture = ''

# Required Modules (will load before this module loads)
RequiredModules = @()

# Required Assemblies
RequiredAssemblies = @()

# PowerShell Scripts (.ps1) that need to be executed before this module loads
ScriptsToProcess = @()

# Type files (.ps1xml) that need to be loaded when this module loads
TypesToProcess = @()

# Format files (.ps1xml) that need to be loaded when this module loads
FormatsToProcess = @()

# 
NestedModules = @()

# List of exportable functions
FunctionsToExport = 'New-BurntToastNotification'

# List of exportable cmdlets
CmdletsToExport = '*'

# List of exportable variables
VariablesToExport = '*'

# List of exportable aliases
AliasesToExport = 'Toast'

# List of all modules contained in this module
ModuleList = @()

# List of all files contained in this module
FileList = @()

# Private data that needs to be passed to this module
PrivateData = ''

}